### ISSUE TITLE
p-calendar styling is incorrect when it is disabled with an icon

### ISSUE THREAD

**Issue by PeterHewat** [primefaces/primeng#10024]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Example**
https://stackblitz.com/edit/primeng-issue-mdc-theme-calendar-with-icon?file=src/app/app.component.html

**Current behavior**
The style of a disabled p-calendar with icon is incorrect
=> Wrong bg-color + hover over it changes style.
This doesn't occur if the calendar icon isn't displayed.

**Expected behavior**
The style of a disabled p-calendar should be correct, irrelevant of if it has an icon or not.

**Minimal reproduction of the problem with instructions**
See Stackblitz Example
*Prerequisite:* Use class p-input-filled & themes/mdc-light-indigo/theme.css.

* **Angular version:** 11.2.6

* **PrimeNG version:** 11.3.1

* **Browser:** all
 
* **Language:** all

**Comment by PeterHewat** [comment]
I have found a workaround. I use the p-calendar in a reactive form. I apply a "disabled" class to styleClass in order to be able to apply the appropriate styling to the disabled calender input. This is very hacky... but it works until a proper fix is available.
```html
<div class="p-field p-float-label">
  <p-calendar
    inputId="myDate"
    formControlName="myDate"
    [showIcon]="true"
    [styleClass]="form.controls.myDate.disabled ? 'disabled' : ''"
  ></p-calendar>
  <label for="myDate">{{'labels.created' | transloco}}</label>
</div>
```
```css
::ng-deep {
  .p-input-filled .p-calendar-w-btn.disabled {
    background-image: linear-gradient(to right, black 10%, transparent 0%) !important;
    background-position: bottom;
    background-size: 4px 1.5px;
    background-repeat: repeat-x;
    input {
      background-image: none;
    }
  }
}
```

**Comment by PeterHewat** [comment]
This fix reveils another bug: Adding p-disabled applies opacity 0.38 twice and we don't want the line under the input since it is already on the parent span. Thus, we have to add this css to fix this:
```css
::ng-deep .p-input-filled .p-disabled > .p-component:disabled {
  opacity: 1;
  background-image: none;
}
```
