### ISSUE TITLE
Scroll not in sync on p-table with frozen columns and virtual scroll

### ISSUE THREAD

**Issue by aliasbody** [primefaces/primeng#10146]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When we enable frozen columns in a table (without virtual scroll) the right table (unfrozen) scrolls both itself and the left (frozen) tables, which in itself is already a bug, but when we add virtual scroll the left side shows scrolls and they only scroll itself, the right bar continues to scroll both (itself and left).

**Expected behavior**
When using the frozen columns, the scroll should happen independant of the table scrolled and it should have the same behavior when including virtualscroll

**Minimal reproduction of the problem with instructions**
(I'll be updating an example in a few minutes, the most important part for me was to show the bug and a solution)

**Bug 1: (Without VirtualScroll -- Can scroll from the right table but not from the left)**
https://primeng-10146-frozen-without-virtualscroll.stackblitz.io

**Bug 2: (With VirtualScroll -- Can scroll from the right and the left table, but the left table make the right one move)**
https://primeng-10146-frozen-with-virtualscroll.stackblitz.io

**Workaround solution:**
https://primeng-10146-workaround.stackblitz.io

**What is the motivation / use case for changing the behavior?**
We we're trying to implementer a table with a scrollable fixed height, frozen columns and virtualscroll.

**Please tell us about your environment:**
Doesn't matter (since it's a bug in the actual code)

* **Angular version:** 5.X
Angular 11.2.x

* **PrimeNG version:** 5.X
PrimeNG 11.3.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All Browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.1.5

* **Node (for AoT issues):** `node --version` =   
v15.13.0

**Solution:**

The solution consists in two steps.

**First step:** We need to remove the scrollbar from the frozen columns table when the virtualscroll is enabled:
```css
.p-datatable .p-datatable-scrollable-view.p-datatable-frozen-view .p-datatable-scrollable-body::-webkit-scrollbar,
.p-datatable .p-datatable-scrollable-view.p-datatable-frozen-view .cdk-virtual-scroll-viewport::-webkit-scrollbar {
  /* Hide scrollbar for Chrome, Safari and Opera */
  display: none;
}
.p-datatable .p-datatable-scrollable-view.p-datatable-frozen-view .p-datatable-scrollable-body,
.p-datatable .p-datatable-scrollable-view.p-datatable-frozen-view .cdk-virtual-scroll-viewport {
  /* Hide scrollbar for IE, Edge and Firefox */
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
  overflow-y: scroll;
  overflow-x: hidden;
}
```

**Second step:** Outside of the p-table code we need to disable the scrollPropagation and override the method ourself (not the cleanest way but it's just a proof of concept)
```typescript
const frozenChild = tables.first.scrollableFrozenViewChild;
const bodyChild   = tables.first.scrollableViewChild;

const frozenTable = (frozenChild.dt.virtualScroll ? frozenChild.virtualScrollBody.getElementRef() : frozenChild.scrollBodyViewChild).nativeElement;
const bodyTable   = (bodyChild.dt.virtualScroll ? bodyChild.virtualScrollBody.getElementRef() : bodyChild.scrollBodyViewChild).nativeElement;

// Frozen Scroll
let frozenScrollTimer;
let frozenIsScrolling = false;
frozenTable.onscroll = (scrollEvent: any) => {
  if (!bodyIsScrolling) {
    frozenIsScrolling = true;
    bodyChild.preventBodyScrollPropagation = true;
    bodyChild.scrollTo({top: scrollEvent.target.scrollTop});
    clearTimeout(frozenScrollTimer);
    frozenScrollTimer = setTimeout(() => { frozenIsScrolling = false; }, 50);
  }
};

// Body Scroll
let bodyScrollTimer;
let bodyIsScrolling = false;
bodyTable.onscroll = (scrollEvent: any) => {
  if (!frozenIsScrolling) {
    bodyIsScrolling = true;
    frozenChild.preventBodyScrollPropagation = true;
    frozenChild.scrollTo({top: scrollEvent.target.scrollTop});
    clearTimeout(bodyScrollTimer);
    bodyScrollTimer = setTimeout(() => { bodyIsScrolling = false; }, 50);
  }
};
```

**In details what this code does is:**
* We init the frozen and body child tables
* We check if it's inside a virtualscroll or not (and use the right one)
* We Set two onscroll methods (one from the frozen and one for the body)
* We use timeout (with a 200ms timer) to avoir having both of them conflicting
* We only leave running the last timer
* We use the p-tables native method to scroll vertically (faster than trying to access the nativeElement and scroll that one)
