### ISSUE TITLE
The width of a p-dropdown and a p-autoComplete inside an p-inputgroup is not adjusted to 100%

### ISSUE THREAD

**Issue by andy01pr** [primefaces/primeng#10635]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-pt1gss?file=src/app/app.component.html

**Current behavior**

The width of a p-dropdown and a p-autoComplete inside an p-inputgroup is not adjusted to 100%. This only occurs in PrimeNG version 12.1.1. Version 12.1.0 worked fine.

**Expected behavior**

The p-dropdown and p-autoComplete width should be 100%.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-pt1gss?file=src/app/app.component.html

**Please tell us about your environment:**

* **Angular version:** 12.2.6

* **PrimeNG version:** 12.1.1

* **Browser:** all

 
* **Language:** TypeScript 4.3.5

**Comment by vinlos** [comment]
I confirm the issue

**Comment by h3llrais3r** [comment]
Having the same issue.
Fixed it by just setting the width of `.p-dropdown` to `auto`.

I had to use a custom class `dropdown` in combination with the `p-inputgroup` class in order to get it working.
You can also ignore this, but then you'll need to make it `auto !important`.
But I rather don't use that, so that's why I force it with the additional class.

```html
<div class="p-inputgroup dropdown">
        <span class="p-inputgroup-addon">Type</span>
        <p-dropdown [options]="videoTypes"></p-dropdown>
</div>
```

```scss
// Inputgroup
.p-inputgroup {

  // Custom support for dropdown
  &.dropdown {
    .p-inputgroup-addon {
      line-height: normal;
    }

    .p-dropdown {
      @include border-radius(0);
      width: auto; // need to auto dropdown label inside inputgroup

      &:last-child {
        @include border-radius(0 3px 3px 0); // in sync with radius of primeng
      }
    }
  }
}
```
