### ISSUE TITLE
Unify Light/Dark themes

### ISSUE THREAD

**Issue by PeterHewat** [primefaces/primeng#10746]
**I'm submitting a feature request**

Currently, light and dark themes are handled by 2 seperate CSS files:
Example of a light theme (saga-blue)
```css
:root {
  --surface-a:#ffffff;
  --surface-b:#f8f9fa;
  // ...
}
```
And for dark theme (arya-blue):
```css
:root {
  --surface-a:#1e1e1e;
  --surface-b:#121212;
  // ...
}
```
These files are identical except for a set of light/dark colors.

A better way of handling light and dark themes would be to only have one CSS file that contains both light and dark colors.

For this, you would have the light colors by default:
```css
:root {
  --surface-a:#ffffff;
  --surface-b:#f8f9fa;
  // ...
}
```
And you would add a dark selector:
```css
html[data-theme=dark] {
  --surface-a:#1e1e1e;
  --surface-b:#121212;
  // ...
}
```
Then, all you would have to do to toggle modes is to set the theme attribute on the HTML element:
```html
<html data-theme="dark">
```
