### ISSUE TITLE
p-scrollPanel : content width is increased by 18px if there is no overflow

### ISSUE THREAD

**Issue by OnkarRuikar** [primefaces/primeng#10968]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
***
Here is the stackblitz [issue demo](https://stackblitz.com/edit/primeng-tabview-demo-qtoxpf?file=src/app/app.component.html)
Issue explained with solution at [stackoverflow](https://stackoverflow.com/a/70349858/15273968)
<br>

**Current behavior**
Due to following default CSS rule:
```CSS
.p-scrollpanel-content {
  height: calc(100% + 18px); 
  width: calc(100% + 18px); /* extra 18px to move scroll out of boundary and hide */
  padding: 0 18px 18px 0;
  position: relative;
  overflow: auto;
  box-sizing: border-box;
}
```
When there is no overflow browser removes the original scrollbars so the `calc(100% + 18px);` adds extra 18px to the width and height.

**Expected behavior**
Content size should remain same regardless of overflow.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tabview-demo-qtoxpf?file=src/app/app.component.html <br>
In this demo if you click on `Header 1` and `Header 2` you'll notice that the scrollpanel content width changes. Because there is no overflow incase of `Header2`

**Proposed solution**
If we make default scrollbars permanently visible then there won't be any dimension changes due to `calc(100% + 18px)` rule.
```CSS
.p-scrollpanel .p-scrollpanel-content {
  overflow-y: scroll !important;
}
```
If we add above CSS rule to the default generated CSS then the issue will be solved easily.

**Please tell us about your environment:**
- stackblitz.com on Windows 10
- browser Chrome 96.0.4664.93 (Official Build) (64-bit) (cohort: Stable)

* **Angular version:** 11.0.9

* **PrimeNG version:** 11.3

* **Browser:** Chrome 96.0.4664.93 (Official Build) (64-bit) (cohort: Stable)
 
* **Language:** all
