### ISSUE TITLE
Horizontal Tree Bug with Material Design Theme

### ISSUE THREAD

**Issue by TeyAbsolut** [primefaces/primeng#11242]
There is an display bug with the horizontal tree when selecting or hovering on a node while using one the Material Design themes.
 
![image](https://user-images.githubusercontent.com/1488854/155970635-c09397d1-fb92-4d75-a36c-9a8193f971f9.png)

Is there a workaround to fix this ?

**Comment by FlipWarthog** [comment]
As a workaround, you can add styles like the follow to override the Material themes' transparent background.

Note, these specific colors are based on Material Indigo Light so you may have to adjust depending on which specific theme you're using.
```css
.p-tree.p-tree-horizontal .p-treenode .p-treenode-content.p-highlight {
  background: #e8eaf6;
}
.p-tree.p-tree-horizontal .p-treenode .p-treenode-content.p-treenode-selectable:not(.p-highlight):hover {
  background: #f5f5f5;
}
```
