### ISSUE TITLE
V13 - Sidebar doesn't remove mask (again)

### ISSUE THREAD

**Issue by QuickScoP3s** [primefaces/primeng#11587]
### Describe the bug

As mentioned in this ticket by multiple people, the same bug is again present in V13 of PrimeNG: #10682 

### Environment

OS: Windows 11 (stable)
IDE: Visual Studio Code (stable)

### Angular version

13.3.10

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

**Comment by QuickScoP3s** [comment]
Issue solved by updating my theme with the following properties:

```css
.p-component-overlay-enter {
   animation: p-component-overlay-enter-animation 150ms forwards;
}

.p-component-overlay-leave {
   animation: p-component-overlay-leave-animation 150ms forwards;
}

@keyframes p-component-overlay-enter-animation {
   from {
      background-color: transparent;
   }
   to {
      background-color: var(--maskbg);
   }
}
@keyframes p-component-overlay-leave-animation {
   from {
      background-color: var(--maskbg);
   }
   to {
      background-color: transparent;
   }
}
```

And don't forget to add `--maskbg: rgba(0, 0, 0, 0.4);` to the `:root` element
