### ISSUE TITLE
Primefonts: Use SVG instead of font

### ISSUE THREAD

**Issue by stewartrutledge** [primefaces/primeng#12648]
### Describe the feature you would like to see added

I'm deploying my app to a platform that has some constraints, one of which is not being to load font files from published applications. This leads to all icons being rendered as boxes with question marks. I can work around this in some cases by using custom font classes with an SVG as the background, like

```css
.chevron-down {
  width: 1.2rem;
  height: 1.2rem;
  color: white;
  fill: white;
  background-image: url("assets/icons/chevron-down.svg");
  @apply text-gray-50
}
```

But this a little time consuming and really not very flexible. I see that primeicons are published as SVGs, it would be great if I could use those directly instead of the font versions.

Is this currently possible? Or would this be a good feature?

### Is your feature request related to a problem?

Icons aren't rendered to do policies on the platform the app is published too.

### Describe the solution you'd like

Use icons that are inlined SVGs instead of fonts.

### Describe alternatives you have considered

Custom classes with svg backgrounds, which works but is time consuming and inflexible.
