### ISSUE TITLE
Clear filter Icon is not showing in p-columnfilter Component

### ISSUE THREAD

**Issue by stefhorst** [primefaces/primeng#12947]
### Describe the bug

The clear filer icon on the columnfilter is not showing if filters ar selected

the variable clearIconTemplate is missing in table.ts

see
  <FilterSlashIcon *ngIf="!clearIconTemplate"/>

### Environment

Angular / primeng

### Angular version

15.2.0

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Select a filter in the p-columnfilter Component
2. the clear button should appear
3. the icon is not visisble

**Comment by mnhock** [comment]
Can confirm this. In the latest version the clear button for column filtering is not shown anymore.

**Comment by Bubiec** [comment]
Seems <filterslashicon> is missing `pi pi-filter-slash` classes. Temporary solution is to manually add styles coming from these classes:
```scss
.p-column-filter-clear-button {
    font-family: 'primeicons';

    filterslashicon {
        &:before {
            content: "\e9b7";
        }
    }
}
```
