### ISSUE TITLE
ColorPicker: *.png missing

### ISSUE THREAD

**Issue by 102-97-98-105** [primefaces/primeng#13820]
### Describe the bug

By following the installation guide the png-files are missing, and the color picker is broken. (fore example the hue.png is missing)

### Environment

Angular CLI: 16.2.4
Node: 18.17.0
Package Manager: npm 9.8.1
Windows: 10
IDE: Intellij Community

### Angular version

16.2.4

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.0

### Steps to reproduce the behavior

0. Angular application setup with sass for styling
1. Follow the installation guide.
2. Use the ColorPicker in a project.

### Expected behavior

![grafik](https://github.com/primefaces/primeng/assets/98735329/44dabf26-cd9b-45b5-ad12-9e88371a9e45)
Displaying that way, no error messages or anything else in dev tools.
Files are in the node_modules folder

**Comment by 102-97-98-105** [comment]
I found a fix: Add the following to the top level styles.sass

`/* You can add global styles to this file, and also import other style files */
.p-colorpicker-panel .p-colorpicker-color
    background: transparent url("./images/color.png") no-repeat left top


.p-colorpicker-panel .p-colorpicker-hue
   background: transparent url("./images/hue.png") no-repeat left top
`

The problem seems to be the styles generator that throws away the css styles of colorpicker-images.css

**Comment by SoyDiego** [comment]
I cannot reproduce.
I added in my project and all is working perfectly.

![image](https://github.com/primefaces/primeng/assets/19764334/add2cebb-7f27-46d8-b846-75f01bb97a83)

Maybe is better if you share a stackblitz or give more information.

Thanks

**Comment by sitterrus** [comment]
@SoyDiego i think the op used sass theme [https://github.com/primefaces/primeng-sass-theme/blob/main/theme-base/components/input/_colorpicker.scss](url) which doesn't have the backround style and indeed there is no background 
![image](https://github.com/primefaces/primeng/assets/40627292/f68ed235-24d3-48b9-9a9f-20c3eb60b072)


Shouldn't colorpicker-images.css be included in colorpicker component?[https://github.com/primefaces/primeng/blob/7216049475cdde34593d321181dbbb174e164dd8/src/app/components/colorpicker/colorpicker.ts#L74C38-L74C38](url)

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a stackblitz reproducer so we can identify the issue clearly?

**Comment by mrafiqk** [comment]
@cetincakiroglu 
Looks like the resource images are corrupted in the latest build. I replaced the images and added some style in css. It worked.

FYI:
style.css / style.scss
```css
/* You can add global styles to this file, and also import other style files */
.p-colorpicker-panel .p-colorpicker-color {
	background: transparent url("assets/img/custom-color.png") no-repeat left top
}


.p-colorpicker-panel .p-colorpicker-hue {
	background: transparent url("assets/img/custom-hue.png") no-repeat left top !important;
}
```

custom-color.png
![custom-color](https://github.com/user-attachments/assets/aefa5064-8e18-4bdc-a559-f058a8695583)

custom-hue.png
![custom-hue](https://github.com/user-attachments/assets/61460c5c-b283-49a4-9ebf-7a78246878d8)
