### ISSUE TITLE
p-password width issue when applying in p-inputgroup

### ISSUE THREAD

**Issue by yongshun950824** [primefaces/primeng#14043]
### Describe the bug

Reported bug in this StackOverflow question: [PrimeNG "p-password" size not working inside a "p-inputgroup"][1].

The `<p-password>` does not fit the content (width) when it is in `p-inputgroup`.

Image:

![][2]

However, I am able to resolve this with

```CSS
.p-inputgroup > p-password > .p-password.p-inputwrapper {
  width: 100%;
}
```

by adding to the global stylesheet.

I wonder whether it is a bug from PrimeNG or expected behavior?

[1]: https://stackoverflow.com/q/77434210/8017690
[2]: https://i.stack.imgur.com/VXIBl.png

### Environment

StackBlitz, user local environment

### Reproducer

To reproduce, uncomment from L3-L5 in global_styles.css

https://stackblitz.com/edit/stackblitz-starters-zdgify?file=src%2Fmain.ts

### Angular version

16.2.12

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Not provided

### Expected behavior

The `<p-password>` should fit the content in `p-input-group`.

**Comment by pavel-pismerov** [comment]
The same issue. Also if styling is applied the eye icon disappears on focus.

**Comment by yongshun950824** [comment]
Hi @pavel-pismerov, the reason why eye icon is not visible as the below styling is applied when the input field is focused.

```CSS
.p-inputgroup > .p-component:focus, .p-inputgroup > .p-element:focus, .p-inputgroup > .p-inputwrapper > .p-component > .p-inputtext:focus, .p-inputgroup > .p-float-label > .p-component:focus {
    z-index: 1;
}
```

You can overwrite the default behavior for the eye icon or `.p-icon-wrapper` with the largest `z-index`. This will result in the icon will be shown.

```CSS
.p-inputgroup > p-password > .p-password.p-inputwrapper > .p-icon-wrapper {
  z-index: 999;
}
```

Also update in the [demo](https://stackblitz.com/edit/stackblitz-starters-zdgify?file=src%2Fglobal_styles.css)
