### ISSUE TITLE
Table > Responsive: stack is equal scroll, stack not showing

### ISSUE THREAD

**Issue by jorgegarinroman-uv** [primefaces/primeng#16291]
### Describe the bug

On a small screen, table responsive scroll and stack operate the same way: stack responsive is lost. 

This error also happens in the primeng guide, in the table > responsive section

### Environment

Chrome Versión 128.0.6613.84 (Build oficial) (64 bits)

### Angular version

17.3.12

### PrimeNG version

17.18.9

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Browser(s)

Chrome

### Expected behavior

The rows should be displayed as a stack facing down.

**Comment by andresrestrepo** [comment]
I can see the same, on version 17.18.8 works fine

**Comment by noradroid** [comment]
i have the same issue
<img width="300" alt="image" src="https://github.com/user-attachments/assets/48f824aa-1ab3-489d-bbd1-e4c31e269d8d">

**Comment by jorgegarinroman-uv** [comment]
temporal solutions:

1. Downgrade to version 17.18.8.

or

2. Apply this CSS

```css
@media screen and (max-width: 992px) {
  .p-datatable-tbody > tr > td > .p-column-title {
    display: block;
  }
  .p-datatable-tbody > tr > td:not(:last-child) {
    border: 0 none;
  }
  .p-datatable-tbody > tr > td {
    display: flex;
    width: 100% !important;
    align-items: center;
    justify-content: space-between;
  }
  .p-datatable-thead > tr > th,
  .p-datatable-tfoot > tr > td {
    display: none !important;
  }
}
```
