### ISSUE TITLE
Component Popover pointing at wrong area

### ISSUE THREAD

**Issue by saiful-70** [primefaces/primeng#16406]
### Describe the bug

Popover pointing at wrong area

![Screenshot from 2024-09-15 16-20-02](https://github.com/user-attachments/assets/3f0d6156-6e16-4303-9afc-76a5a84c5c8c)

### Environment

Using latest primeng with latest angular 

### Angular version

18.2.0

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

**Comment by afermon** [comment]
Hi, 

This is reproducible on PrimeNG 19  and Angular 19.

https://stackblitz.com/edit/stackblitz-starters-fnqruhfa

<img width="438" alt="image" src="https://github.com/user-attachments/assets/c6bca232-0eae-452a-bf0f-bf4bafe82c1f" />

It is related to the fixed left position of the before section on the popover 
https://github.com/primefaces/primeng/tree/master/packages/primeng/src/popover/style/popoverstyle.ts

Lines 41 to 50
```scss
.p-popover:after,
.p-popover:before {
    bottom: 100%;
    left: ${dt('popover.arrow.offset')};
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
}
```

Maybe `popover.arrow.offset` can have left and right variants and set one to "unset" value?
or calculate the appropriate positioning dynamically based on the trigger element position and the size of the contents.
