### ISSUE TITLE
Component: Color Picker - Pop-up not showing the full palette when clicked, just the current selected colour

### ISSUE THREAD

**Issue by Eagle-Tim** [primefaces/primeng#16449]
### Describe the bug

When using the color picker, on clicking the button to show the popup, it is just showing a single square of one colour (the currently selected colour), rather than a full palette of colours. The slider also shows no colours

![image](https://github.com/user-attachments/assets/485510a1-50e5-4b4c-90fd-fe21ec28d1c3)

Note, this screenshot is taken from the Stackblitz linked to from PrimeNg's documentation

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/acucgw?file=package.json

### Angular version

17.3.10

### PrimeNG version

17.18.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

### Steps to reproduce the behavior

1. Set up a color picker component
2. Click the button to open it

Color picker pop-up only shows one colour (the selected one), and slider is blank

### Expected behavior

Normal color palette and slider is shown

**Comment by simonstaffgenius** [comment]
I got the same issue. Also happened like 5 days ago.
It seems like the `./media/hue.png` and `./media/color.png` are missing.

**Comment by daniel1919-00** [comment]
I got the same issue after updating to 17.18.11.

![image](https://github.com/user-attachments/assets/fd26f82d-5929-417f-ae3e-540c430de164)

**Comment by PrimeFactor7** [comment]
Have the issue with color picker with inline mode as well.  I updated to 17.18.11 tried to rollback to my previous version 17.18.5 and the issue persists

**Comment by simonstaffgenius** [comment]
As a temporary workaround, you can replace the files under `node_modules/primeng/resources`.

For color.png use:
![color](https://github.com/user-attachments/assets/87e3b34c-ec87-4892-a8d9-4cf009c69d90)

For hue.png use:
![hue](https://github.com/user-attachments/assets/dd80c6be-f20a-4a00-aca2-283da2314d19)

Note: This only works temporarily until you reinstall with your packages.

**Comment by arnoudb** [comment]
> Have the issue with color picker with inline mode as well. I updated to 17.18.11 tried to rollback to my previous version 17.18.5 and the issue persists

reverting to 17.18.10 worked for me

**Comment by faelpinho** [comment]
Related to issue #13820

I'm currently using the version 17.18.10. The PNG still not loading for me.

Thanks to @mrafiqk for a good workaround:

```css
/* You can add global styles to this file, and also import other style files */
.p-colorpicker-panel .p-colorpicker-color {
	background: transparent url("assets/img/custom-color.png") no-repeat left top
}


.p-colorpicker-panel .p-colorpicker-hue {
	background: transparent url("assets/img/custom-hue.png") no-repeat left top !important;
}
```
