### ISSUE TITLE
Component: Primeng color picker is not working

### ISSUE THREAD

**Issue by DHANUSH-31** [primefaces/primeng#16586]
### Describe the bug

angular version : 14
prime ng version : 9.1.3
color picker is not working 

### Environment

local 

### Angular version

14.3.0

### PrimeNG version

9.1.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10.8.2

### Browser(s)

chrome latest

### Steps to reproduce the behavior

we have added the code for color picker and the shades are static 
![image](https://github.com/user-attachments/assets/f7c636e3-c612-40f6-90c4-b5f3c0d34f4d)

### Expected behavior

![image](https://github.com/user-attachments/assets/7c7fd673-8633-4292-9145-d40f436fc2d3)

**Comment by hsel-dove** [comment]
Having the same issue on Angular v18 & PrimeNg v17.18.11.

**Comment by DHANUSH-31** [comment]
any solution ?

**Comment by mrafiqk** [comment]
Looks like the resource images are corrupted. I replaced the images and added some style in css. It worked.
FYI:
style.css / style.scss
```css
/* You can add global styles to this file, and also import other style files */
.p-colorpicker-panel .p-colorpicker-color {
	background: transparent url("assets/img/custom-color.png") no-repeat left top
}


.p-colorpicker-panel .p-colorpicker-hue {
	background: transparent url("assets/img/custom-hue.png") no-repeat left top !important;
}
```

custom-color.png
![custom-color](https://github.com/user-attachments/assets/aefa5064-8e18-4bdc-a559-f058a8695583)

custom-hue.png
![custom-hue](https://github.com/user-attachments/assets/61460c5c-b283-49a4-9ebf-7a78246878d8)
