### ISSUE TITLE
Scrollable Tabs Feature

### ISSUE THREAD

**Issue by serak** [primefaces/primeng#1701]
I have now gotten into primeng Recently and I am in love with it but one thing that still bug's me is the when you keep adding tabs it wont scroll it just start pilling up vertically.

It would be great if they have the same feature as angular material Tab Scroll

with regards
serak

**Comment by cagataycivici** [comment]
We have that in PrimeFaces, could do the same for NG as well;

**Comment by morganRotaStabelli** [comment]
It would be perfect, do you already know when it might come?

**Comment by cagataycivici** [comment]
In 4.1.1.

**Comment by serak** [comment]
now i am the happiest MAN. its would be even great if it can be scrolled on focus and scroll. 

like angular material does..

Thanks for effort in adding this feature.

**Comment by gieboyz** [comment]
in 4.1.1
still not working using scrollable="true" like https://www.primefaces.org/showcase/ui/panel/tabView.xhtml

can you give more example for this features?

**Comment by serak** [comment]
i ask for primeng and i get a response for primeface,,

what just happpend?

**Comment by lanbin45** [comment]
@gieboyz Did you try scrollable tabview in primeNG of latest version? For V4.2, the property ‘scrollable’ did not work for me.

**Comment by luboslav** [comment]
You can allow horizontal scrolling with css.

```css
.ui-tabview .ui-tabview-nav {
    white-space: nowrap;
    overflow-x: auto;
}

.ui-tabview .ui-tabview-nav li {
    display: inline-block;
    float: none;
}
```
