### ISSUE TITLE
p-checkbox: doesn't work with binary false [19.0.0]

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#17140]
### Describe the bug

- checkbox selection doesn't work if binary is set to false.

### Environment

NA

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-hfugrqpy?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json

### Angular version

19.x

### PrimeNG version

19.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Steps to reproduce the behavior

open stackblitz & try to select checkbox.

### Expected behavior

user should be able to select even if `binary` is set to false. `false` is also a default value for this option.

**Comment by payalasodariya** [comment]
While reviewing your code [here...,](https://stackblitz.com/edit/stackblitz-starters-hfugrqpy?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json) it seems that although you are attempting to set a binary value to false, you are actually providing the boolean value false instead in ngmodel.

One workaround with this is providing value as below(just for example),

ts file:
`checked = signal([]);`

html:
`<p-checkbox value="test" [(ngModel)]="checked" [binary]="false" />`

**Comment by RankXen** [comment]
@payalasodariya @cetincakiroglu 
Not creating a new issue since this one exists. The repro example @imaksp provided does not properly show the problem.

You'll get errors when you use the code like so:
`<p-checkbox [(ngModel)]="checked" [binary]="false" [indeterminate]="true" />`

I've **forked the stackblitz from the primeng docs and only changed binary to false**.
When you try to use the checkbox you'll get an error: **currentModelValue.filter is not a function**

Stackblitz (primeng 18, same problem on latest v19):
https://p6hbpmyf.stackblitz.io

**Comment by johnhwright** [comment]
Also trying to upgrade from v17 and ran into this.  While we're not experiencing any "errors", the migration guide says:
> Removed Components
> TriStateCheckbox | Use Checkbox with indeterminate option.

But these things are definitely not equivalent ([See the official V17 examples here](https://v17.primeng.org/tristatecheckbox) 🤦‍♂️). While you can bind the initial model value to be `null` to show the indeterminate state, as soon as the checkbox has been interacted with there is no way to cycle it back around to `null` value. Which doesn't work when building forms used for filters where you need the `true`/`false` value if they want to filter but also `null` if they want to skip that criteria entirely.

**Comment by adama357** [comment]
As stated above, the indeterminate option doesn't make a Checkbox behave like a TriStateCheckbox. 

In order for the Checkbox component to actually cover the functionality of the TriStateCheckbox, there would need to be an additional `triState` property added. **I created a discussion about this [here](https://github.com/orgs/primefaces/discussions/3683).**

**Comment by adri95cadiz** [comment]
for the moment while this is solved I migrated the v17 version of tristate checkbox to be compatible with the newer versions.

I'm attaching the modified files if you need to use this as a temporary workaround while the indeterminate state is fixed, or if it is not then this is the only solution that I can think of, with the hassle of having to maintain this small component.

[tristate.zip](https://github.com/user-attachments/files/19234327/tristate.zip)

For the styling I had to add these lines of css to my component so it looks like the normal checkbox:
`
    .p-checkbox .p-checkbox-box {
      margin-top: 0rem;
      &:not(:empty) {
        border-color: var(--p-checkbox-checked-border-color);
        background: var(--p-checkbox-checked-background);
        .p-iconwrapper > .p-checkbox-icon {
          color: var(--p-checkbox-icon-checked-color);
        }
      }
`

**Comment by adri95cadiz** [comment]
Well, it depends.

In my case we use it to filter boolean fields, if it is inactive the values are not filtered, true for filtering true values and false for false.

This is a pretty elegant solution, it is intuitive for our users and is a very space optimal way of showing this.

At the moment we have no intention of changing this behaviour as it is our the way of solving this we're most satisfied with and for us it's a shame the functionality has lost support without a proper replacement.

**Comment by adama357** [comment]
Actually, the repro @RankXen made _shouldn't_ work. The `p-checkbox` has `[binary]="false"` but it's bound to `checked`, which is just a single Boolean. In this example, binary should be true. 

@cagataycivici @cetincakiroglu I think there is a lot of confusion going on with this issue. Setting the `binary` property to false isn't intended to make a checkbox behave like a TriStateCheckbox; it's for scenarios where multiple checkboxes are being used together as a group. (See [this](https://primeng.org/checkbox#group) example in the docs.) 

The real problem is that people are trying to follow [the PrimeNG migration guide's](https://primeng.org/guides/migration) suggestion for how to replace their TriStateCheckboxes: "Use Checkbox with indeterminate option." 

Firstly, it doesn't seem like TriStateCheckbox should've been removed altogether in v18, since it wasn't deprecated in v17. (An issue was created about that [here](https://github.com/primefaces/primeng/issues/17137), but it was closed.)

Secondly, the migration guide's suggestion doesn't work, because indeterminate Checkboxes function differently than TriStateCheckboxes. The whole point of the TriStateCheckbox is that you can cycle **back to a null value.** 

That's not what indeterminate checkboxes are for. You can read about the standard behavior of the `indeterminate` checkbox state in [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/checkbox#using_checkbox_inputs). 

So if you want the Checkbox component to behave like a TriStateCheckbox, you'd need to add a separate `triState` property. But as I mentioned above, if you're going to merge the functionally of TriStateCheckbox into one of the other components, the ToggleButton would be a better choice imho. ToggleButtons have labels, and a TriStateCheckbox without a label would be very confusing.

**Comment by filiptrivan** [comment]
Any updates?

**Comment by filiptrivan** [comment]
I should probably add “PrimeNG overrider” to my CV 😂.

Here’s my workaround for reactive controls:

**HTML:**
```html
<div style="margin-top: 0.5rem; position: relative;">
        <p-checkbox
        [class]="control.value === false ? 'p-checkbox-false' : ''"
        [formControl]="control"
        [value]="inlineLabel"
        [binary]="true"
        (onChange)="change()"
        />
        <i 
        *ngIf="control.value === false" 
        class="pi pi-times p-checkbox-false-icon" 
        [style.color]="control.disabled ? 'var(--p-checkbox-icon-disabled-color)' : 'var(--p-checkbox-icon-checked-color)'"
        ></i>
</div>
```

**ts:**
```ts
// ...
change = () => {
    if (this.control.value === false) 
        this.control.setValue(true);
    else if (this.control.value === true) 
        this.control.setValue(null);
    else 
        this.control.setValue(false);
}
// ...
```

**scss:**
```css
::ng-deep {
    .p-checkbox-false {
        .p-checkbox-box {
            border-color: var(--p-checkbox-checked-border-color);
            background: var(--p-checkbox-checked-background);
        }
        .p-checkbox:not(.p-disabled):has(.p-checkbox-input:hover) .p-checkbox-box {
            border-color: var(--p-checkbox-checked-hover-border-color) !important;
            background: var(--p-checkbox-checked-hover-background) !important;
        }
        .p-checkbox-false:has(.p-checkbox.p-disabled) .p-checkbox-false-icon {
            color: var(--p-checkbox-icon-disabled-color) !important;
        }
    }
}

.p-checkbox-false-icon {
    position: absolute; 
    top: 3px; 
    left: 2.7px; 
    font-size: 12.25px; 
    color: var(--p-checkbox-icon-checked-color);
}
```

**Demo:**
https://github.com/user-attachments/assets/dfb9478c-00da-46f3-a6b4-62a8eddb634a

**Comment by sergiorey23** [comment]
@filiptrivan  @adama357 
 Here’s my workaround (custom controls) for ngModel, formControl and reactive forms:

**HTML**:

```html
<div style="margin-top: 0.5rem; position: relative">
	<p-checkbox
		[inputId]="inputId"
		[name]="name ?? ''"
		[class]="value === false ? 'p-checkbox-false' : ''"
		[binary]="true"
		[ariaLabelledBy]="ariaLabelledBy"
		[ariaLabel]="ariaLabel"
		[tabindex]="tabindex"
		[ngModel]="value"
		[style]="style"
		[disabled]="disabled ?? false"
		[readonly]="readonly ?? false"
		[required]="required ?? false"
		[autofocus]="autofocus"
		[trueValue]="trueValue"
		[falseValue]="falseValue"
		[inputStyle]="inputStyle"
		[styleClass]="styleClass"
		[inputClass]="inputClass"
		[size]="size"
		[checkboxIcon]="checkboxIcon"
		(ngModelChange)="change($event)"
		(onFocus)="onFocus.emit($event)"
		(onBlur)="onBlur.emit($event)" />
	<i
		*ngIf="value === false"
		class="pi pi-times p-checkbox-false-icon"
		[style.color]="disabled ? 'var(--p-checkbox-icon-disabled-color)' : 'var(--p-checkbox-icon-checked-color)'"></i>
	<label *ngIf="label" [for]="inputId" class="ml-2">{{ label }}</label>
</div>
```

**TS**:

```typescript
import { NgIf } from '@angular/common';
import { Component, forwardRef, Input } from '@angular/core';
import { FormsModule, NG_VALUE_ACCESSOR } from '@angular/forms';
import { Checkbox, CheckboxChangeEvent, CheckboxStyle } from 'primeng/checkbox';

@Component({
	selector: 'tri-state-checkbox',
	imports: [Checkbox, FormsModule, NgIf],
	templateUrl: './checkbox.component.html',
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: forwardRef(() => TriStateCheckbox ),
			multi: true
		},
		CheckboxStyle
	],
	styleUrls: ['./checkbox.component.scss']
})
export class TriStateCheckbox extends Checkbox {
	@Input() label?: string;

	change(event: CheckboxChangeEvent) {
		if (this.indeterminate) {
			if (this.value === null || this.value === undefined) this.value = this.trueValue;
			else if (this.value === this.trueValue) this.value = this.falseValue;
			else this.value = null;
			this.onModelChange(this.value);
			this.onChange.emit({ checked: this.value, originalEvent: event.originalEvent });
		} else {
			this.updateModel(event.checked);
		}
	}

    override writeValue(value: any): void {
		super.writeValue(value);
		this.value = value;
	}
}
```

**SCSS**:

```scss
::ng-deep {
    .p-checkbox-false {
        .p-checkbox-box {
            border-color: var(--p-checkbox-checked-border-color);
            background: var(--p-checkbox-checked-background);
        }

        .p-checkbox:not(.p-disabled):has(.p-checkbox-input:hover) .p-checkbox-box {
            border-color: var(--p-checkbox-checked-hover-border-color) !important;
            background: var(--p-checkbox-checked-hover-background) !important;
        }

        .p-checkbox-false:has(.p-checkbox.p-disabled) .p-checkbox-false-icon {
            color: var(--p-checkbox-icon-disabled-color) !important;
        }
    }
}

.p-checkbox-false-icon {
    position: absolute;
    top: 3px;
    left: 2.7px;
    font-size: 12.25px;
    color: var(--p-checkbox-icon-checked-color);
}
```

It works perfect. It fixes the indeterminate property logic from primeng,
