### ISSUE TITLE
Floatlabel overlaps placeholder

### ISSUE THREAD

**Issue by docentYT** [primefaces/primeng#17260]
### Describe the bug

When the floatlabel is displayed on the ‘input’ element, the placeholder is visible so that the two texts overlap. In primeng version 17, the placeholder was only displayed when the input was active and the floatlabel was displayed over the field.

![{4A1476A0-A9BD-49D7-A0DE-9FEC55FA5475}](https://github.com/user-attachments/assets/2d079072-7590-4ccb-bad0-40bcc08d91e5)

### Reason for not contributing a PR

- [X] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/github-n5jhznk4?file=src%2Fapp%2Fapp.component.html

### Environment

Nx monorepo with angular app

### Angular version

19.0.5

### PrimeNG version

v19

### Node version

22.12.0

### Steps to reproduce the behavior

1. Check results for:
```ts
<p-floatLabel>
  <input type="text" pInputText id="website" placeholder="placeholder" />
  <label for="website">Label</label>
</p-floatLabel>
```

### Expected behavior

The placeholder should be hidden when the floatlabel is displayed on the input field.

**Comment by cagataycivici** [comment]
This is by design, Float Label is a placeholder itself, you can't have two placeholders. Correct usage is;

```html
<p-floatLabel>
  <input type="text" pInputText id="website" />
  <label for="website">Website</label>
</p-floatLabel>
```

**Comment by docentYT** [comment]
If Float Label is a placeholder, why isn't it called a 'Float Placeholder'?

**Comment by docentYT** [comment]
If someone is looking for workaround add this css to preset definition:
```css
.p-floatlabel:not(:has(input:focus)) input::placeholder,
.p-floatlabel:not(:has(input.p-filled)) input::placeholder,
.p-floatlabel:not(:has(input:-webkit-autofill)) input::placeholder,
.p-floatlabel:not(:has(textarea:focus)) textarea::placeholder,
.p-floatlabel:not(:has(textarea.p-filled)) textarea::placeholder,
.p-floatlabel:not(:has(.p-inputwrapper-focus)) input::placeholder,
.p-floatlabel:not(:has(.p-inputwrapper-filled)) input::placeholder {
    color: transparent !important;
}

.p-floatlabel:has(input:focus) input::placeholder,
.p-floatlabel:has(input:-webkit-autofill) input::placeholder,
.p-floatlabel:has(textarea:focus) input::placeholder,
.p-floatlabel:has(.p-inputwrapper-focus) input::placeholder {
    color: var(--p-inputtext-placeholder-color) !important;
}
```
