### ISSUE TITLE
ConfirmPopup arrow and position wrong when not enough space to the right or bottom

### ISSUE THREAD

**Issue by pablopaz** [primefaces/primeng#17272]
### Describe the bug

When there is not enough space to the right of the element to fit the popup, the arrow does not point to the target. When there is not enough space to the bottom, the popup is not well positioned.

Additionally, when using a single `<p-confirm-popup />` component, when clicking another button with a popup open, it does not close the previous and instead shows the new popup in the same position as the previous. I would expect it to close the previous and show the new popup relative to the new target.

### Reason for not contributing a PR

- [X] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/github-zfsdrqay?file=src%2Fapp%2Fapp.component.html

### Environment

Windows

### Angular version

19.0.5

### PrimeNG version

v19

### Steps to reproduce the behavior

See stackblitz demo.

### Expected behavior

The arrow should point to the target element and the popup should be positioned over the target with the arrow pointing down when there is not space to the bottom.

**Comment by marianmuresan** [comment]
This issue it seems to be because of a name convention instead of p-confirmpopup-flipped is p-confirm-popup-flipped. And the left attribute is not accounting for --overlayArrowLeft, you can use the following css to a temporary fix:

```css
// arrow alignment for confirmation popup
.p-confirm-popup-flipped:after,
.p-confirm-popup-flipped:before {
    bottom: auto !important;
    top: 100% !important;
}

.p-confirm-popup-flipped:after {
    border-bottom-color: transparent !important;
    border-top-color: var(--p-confirmpopup-border-color) !important;
}

.p-confirm-popup-flipped:before {
    border-bottom-color: transparent !important;
    border-top-color: var(--p-confirmpopup-border-color) !important;
}

.p-confirmpopup:after,
.p-confirmpopup:before {
    left: var(--overlayArrowLeft) !important;
}
```

**Comment by marianmuresan** [comment]
For those who wants a quick fix: 

```css
// arrow alignment for confirmation popup
.p-confirm-popup-flipped:after,
.p-confirm-popup-flipped:before {
    bottom: auto !important;
    top: 100% !important;
}

.p-confirm-popup-flipped:after {
    border-bottom-color: transparent !important;
    border-top-color: var(--p-confirmpopup-border-color) !important;
}

.p-confirm-popup-flipped:before {
    border-bottom-color: transparent !important;
    border-top-color: var(--p-confirmpopup-border-color) !important;
}

.p-confirm-popup-flipped {
    margin-top: calc(var(--p-confirmpopup-gutter) * -1) !important;
    margin-bottom: var(--p-confirmpopup-gutter) !important;
}

.p-confirmpopup:after,
.p-confirmpopup:before {
    left: calc(var(--overlayArrowLeft) + var(--p-confirmpopup-arrow-offset)) !important;
}
```
The css is as p-confirmpopup-flipped but the class added is p-confirm-popup-flipped, and the left attribute does not accounts for overlayArrowLeft.

## Update V21 11/03/2026
In version 21 the variable **overlayArrowLeft** was changed to **--p-confirmpopup-arrow-left**

so this 
```css
.p-confirmpopup:after,
.p-confirmpopup:before {
    left: calc(var(--overlayArrowLeft) + var(--p-confirmpopup-arrow-offset)) !important;
}
```
becomes this
```css
.p-confirmpopup:after,
.p-confirmpopup:before {
    left: calc(var(--p-confirmpopup-arrow-left) + var(--p-confirmpopup-arrow-offset)) !important;
}
```
I didn't create another PR as the old was not added anyway.
