### ISSUE TITLE
Autocomplete validation broken visuals

### ISSUE THREAD

**Issue by PattySantos** [primefaces/primeng#1776]
Olá, estou com um problema para colocar uma validação do form reative, ng-invalid no autocomplete,só consigo colocar no <p-autocomplete o ngClass, mas preciso colocar p-inputtext, para que a borda a esquerda fique dentro do componente autocomplete. Por favor me ajudem 

Hello, I have a problem to put a validation of form reative, ng-invalid in autocomplete, I can only put in <p-autocomplete ngClass, but I need to put p-inputtext, so that the left border is inside the autocomplete component. Please help me
![autocompleteprime](https://cloud.githubusercontent.com/assets/9416155/21808182/3aa93440-d729-11e6-815f-5a22c75ed2f2.png)

**Comment by cagataycivici** [comment]
Is it a multi autocomplete, which theme is it?

**Comment by PattySantos** [comment]
Hello, it's the basic autocomplete and the bootstrap theme is free.

**Comment by PattySantos** [comment]
Correcting, we are using the omega free theme.

**Comment by alezhu** [comment]
Try this
```css
.ng-valid[required], .ng-valid.required {
    border-left: 5px solid #42A948; /* green */
}

.ng-invalid:not(form) {
    border-left: 5px solid #a94442; /* red */
}

p-autocomplete.ng-invalid {
    border-left: 0 none;
}

p-autocomplete.ng-dirty.ng-invalid > .ui-autocomplete > .ui-inputtext,
p-autocomplete.ng-invalid > .ui-autocomplete > .ui-inputtext[required] {
    border-left: 5px solid #a94442; /* red */
    border-bottom: 1px solid #d6d6d6; /* Theme specific */
}

p-autocomplete.ng-valid[required] > .ui-autocomplete > .ui-inputtext,
p-autocomplete.ng-valid.required > .ui-autocomplete > .ui-inputtext,
p-autocomplete.ng-valid > .ui-autocomplete > .ui-inputtext[required] {
    border-left: 5px solid #42A948; /* green */
}

p-autocomplete > .ui-autocomplete > .ui-inputtext {
    padding: 6px 12px;
}
```
