### ISSUE TITLE
How to modify the scrollbar style of p-dialog when using appendTo?

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [primefaces/primeng#17890]
```html
p-dialog
  header="header"
  [modal]="false"
  [style]="{ 'height': dialogHeight + 'px', 'width': dialogWidth + 'px' }"
  [(visible)]="visible"
  [resizable]="true"
  appendTo="body"
  [maximizable]="true"
  >
```
**I can add the following styles in the style.scss file to globally modify the scrollbar style. However, how can I modify the scrollbar style for a specific p-dialog?**
```css
::-webkit-scrollbar {
  width: 11px;
  height: 11px;
}
```
