### ISSUE TITLE
p-calendar in p-inputgroup styling breaks component completely

### ISSUE THREAD

**Issue by sthompson-celerity** [primefaces/primeng#18492]
### Describe the bug

This ticket is still broken: #12558, but now a little worse...

Here is what it looks like right now:
![Image](https://github.com/user-attachments/assets/d7167a32-c98a-4e7f-84f6-e5eb1b1c099e)

### Reason for not contributing a PR

- [ ] Lack of time
- [x] Unsure how to implement the fix/feature
- [x] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/snpfydgy?file=src%2Fapp%2Finput-group-basic-demo.html

### Environment

primeng v19 
angular 19 but it can be reproduced in others I belive

### Angular version

19+

### PrimeNG version

v19

### Steps to reproduce the behavior

make an input group and take a look
```
  <p-inputgroup>
    <p-inputgroup-addon>www</p-inputgroup-addon>
    <p-datepicker [(ngModel)]="text2" placeholder="Website" />
    <p-inputgroup-addon>.com</p-inputgroup-addon>
  </p-inputgroup>
```

### Expected behavior

something like this:

<img width="691" alt="Image" src="https://github.com/user-attachments/assets/eb34b48b-81d9-4da7-b88c-88c8896a509f" />

**Comment by john8329** [comment]
It's something they haven't fixed in years. Use this:
```css
// Fix p-datepicker not adapting in p-inputgroup
.p-inputgroup p-datepicker {
  display: inline-flex;
  position: relative;
}

.p-inputgroup > .p-inputgroupaddon + p-datepicker .p-datepicker-input {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}

.p-inputgroup > p-datepicker:has(+ .p-inputgroupaddon) .p-datepicker-input {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
```
