### ISSUE TITLE
Example for [styleClass]

### ISSUE THREAD

**Issue by malorus** [primefaces/primeng#4014]
Could someone provide an example of how to use the `styleClass` property? I tried 

```html
<p-toggleButton [styleClass]="'test'"></p-toggleButton>
```

In my css-file I have:

```css
.test { background: red; color: yellow;}
```

But this does not work at all. An example would be great.
