### ISSUE TITLE
4.3.0-rc.2 generated css error

### ISSUE THREAD

**Issue by johankvint** [primefaces/primeng#4300]
The generated css contains error, seams like scss did not generate correctly keeping the `&`.

At line 4337:

``` css
.ui-progress-spinner {
    position: relative;
    margin: 0 auto;
    width: 100px;
    height: 100px;
    display: inline-block;
    
    &:before {
        content: '';
        display: block;
        padding-top: 100%;
    }
}
```
