### ISSUE TITLE
5.0.0-rc.0 generated css error

### ISSUE THREAD

**Issue by johankvint** [primefaces/primeng#4386]
At line 182 in generated primeng.css in npm package:

```css
input[type="button" i], 
input[type="submit" i], 
input[type="reset" i], 
input[type="file" i]::-webkit-file-upload-button, 
button {
    -moz-border-radius: 0;
    -webkit-border-radius: 0;
    border-radius: 0;
}
```
