### ISSUE TITLE
support for scrolling inside sidebar

### ISSUE THREAD

**Issue by dolphinsd** [primefaces/primeng#9055]
sidebar is a great control to use for quick data entry

there seems to be no way to enable scroll inside sidebar if form is too long?

consider adding 
    overflow-y: scroll; to body .ui-sidebar

**Comment by eastjie** [comment]
In my PrimeNG project on Angular 9, I have tried a workaround to use "p-scrollPanel" in sidebar with fix height, but after updating to ng 10. The workaround doesn't work any more. Hope to a solution and also in the documentation. Thanks very much.

**Comment by KeithGillette** [comment]
We are able to enable scrolling `p-sidebar` as follows:

**component.scss**
```css
// Must be outside of `:host` to apply inside `p-sidebar`
::ng-deep {
  .p-sidebar-content {
    height: 100%; // If within a fixed-height parent element, otherwise set to fixed height;
  }
}
```

**component.html**
```html
<p-sidebar appendTo="body" styleClass="p-0">
  <div  class="d-flex flex-column justify-content-start">
    <div>Sticks to sidebar top</div>
    <div class="flex-grow-1 overflow-auto">Grows and scrolls</div>
    <div class="align-bottom">Sticks to sidebar bottom</div>
  </div>
</p-sidebar>
```
This simplified example uses Bootstrap styles to achieve the scrolling middle `div`, as that's what we use in our project, but the equivalent PrimeFlex or custom classes could be substituted.
