### ISSUE TITLE
table width problem with responsive mode and colgroup

### ISSUE THREAD

**Issue by jafio** [primefaces/primeng#9444]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-r7qbww?file=src/app/app.component.ts

**Current behavior**

When the table have `<colgroup>`, it prevent the responsive mode to take all the width of the table. For exemple, I have two columns in the table of my plunker so the content takes only the half of the table in responsive mode.

**Expected behavior**

The content of a table in responsive mode should take all the width of the table no matter if I have or not `<colgroup>`
**Minimal reproduction of the problem with instructions**

1. Create a table with `<colgroup>` and enable responsive mode
2. open your browser and set a small width for the window of your browser to see the table in responsive mode
3. You should see that the content of the table doesn't take all the with of the table

**Please tell us about your environment:**

* **Angular version:** 10.0.6
* **PrimeNG version:** 10.0.3
* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   13.14.0

**Comment by jafio** [comment]
The problem is still there with version  11.2.3. And if someone has the same problem, you can add the following style to a global css file as a workaround:
```css
@media (max-width: 40em) {
    .p-datatable.p-datatable-responsive colgroup col:first-child {
        width: 100%;
    }

    .p-datatable.p-datatable-responsive colgroup :not(:first-child) {
        width: 0;
    }
}
```
