### ISSUE TITLE
p-dropdown doesn't fit correctly in a p-inputgroup

### ISSUE THREAD

**Issue by john8329** [primefaces/primeng#9741]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Plunkr Case (Bug Reports)**
https://github-jltrhy-tmo8hc.stackblitz.io

**Current behavior**
As you can see the inputgroup doesn't grow well when using a p-dropdown. It should behave as <input> in theory. I can't even see a demo of this in the documentation, perhaps it hasn't been considered.

The borders are wrong on the left and sometimes even the height has issues. I had to implement some library-wide fixes in my code to make it work.

* **Angular version:** 10.2

* **PrimeNG version:** 10.0.6 LTS

Also I should reference [this issue](https://github.com/primefaces/primeng/issues/7224), seems related.

**Comment by j0hnwhyte** [comment]
Also I wanna share a dirty workaround applied as a global style to fix this thing. Took me a while to figure out.

```typescript
p-dropdown {
  display: grid;
  flex: 1 1 auto;
  width: 1%;

  .p-dropdown {
    height: 100%;
    width: 100%;
    overflow: hidden;
  }
}

.p-inputgroup p-dropdown:not(:last-child) .p-dropdown {
  border-right: 0;
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}

.p-inputgroup p-dropdown:not(:first-child) .p-dropdown {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
```

**Comment by flkeller** [comment]
in addition here is a solution including FloatLabel:
```
.p-inputgroup {
  .p-float-label{
      &:not(:last-child){
          .p-dropdown {
              border-right: 0;
              border-top-right-radius: 0;
              border-bottom-right-radius: 0;
          }
      }
      &:not(:first-child){
          .p-dropdown {
              border-top-left-radius: 0;
              border-bottom-left-radius: 0;
          }
      }
  }
  p-dropdown {
      display: grid;
      flex: 1 1 auto;
      width: 1%;
  
      .p-dropdown {
          height: 100%;
          width: 100%;
          overflow: hidden;
      }
  
      &:not(:last-child){
          .p-dropdown {
              border-right: 0;
              border-top-right-radius: 0;
              border-bottom-right-radius: 0;
          }
      }
      &:not(:first-child){
          .p-dropdown {
              border-top-left-radius: 0;
              border-bottom-left-radius: 0;
          }
      }
  }
}
```

**Comment by h3llrais3r** [comment]
Having the same issue.
Fixed it by just setting the width of `.p-dropdown`

```html
<div class="p-inputgroup dropdown">
        <span class="p-inputgroup-addon">Type</span>
        <p-dropdown [options]="videoTypes"></p-dropdown>
      </div>
```

````scss
// Inputgroup
.p-inputgroup {

  // Custom support for dropdown
  &.dropdown {
    .p-inputgroup-addon {
      line-height: normal;
    }

    .p-dropdown {
      @include border-radius(0);
      width: auto; // need to auto dropdown label inside inputgroup

      &:last-child {
        @include border-radius(0 3px 3px 0); // in sync with radius of primeng
      }
    }
  }
}
```
